# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate_sso:
    aliases:
      - gen_sso
    desc: "Generate code from proto files"
    cmds:
      - export GO_PATH=~/go
      - export PATH=$PATH:/$GO_PATH/bin
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  generate_finance:
    aliases:
      - gen_fin
    desc: "Generate code from proto files"
    cmds:
      - go mod tidy
      - export GO_PATH=~/go
      - export PATH=$PATH:/$GO_PATH/bin
      - protoc 
        -I proto proto/finance/*.proto 
        --go_out=./gen/go/ 
        --go_opt=paths=source_relative 
        --go-grpc_out=./gen/go/ 
        --go-grpc_opt=paths=source_relative
      - protoc
        -I proto/finance/ finance.proto 
        --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts
        --js_out=import_style=commonjs,binary:./gen/ts/finance
        --ts_out=service=grpc-web:./gen/ts/finance        